# Generated by Django 3.2.3 on 2021-12-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_auto_20211122_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en instance', 'en instance'), ('non livré', 'non livré'), ('livré', 'livré"')], max_length=200, null=True),
        ),
    ]
